Let `run-tests` display more `check-info`
Codewars/codewars-rackunit pull request #3
Opened 2019-03-23 08:38 UTC by yfzhe

As #2 mention, `run-tests` now only display 'actual and 'excepted `check-info`, more info like message are missing.

This PR add a #:mode keyword argument, whose value can be: 'quiet, 'simple, 'custom, and 'all.

- Quiet mode displays message, actual, and excepted;
- Simple mode displays name, location, message, actual, and excepted;
- Custom mode displays user custom `check-info`s (using `with-check-info`) and all above;
- All mode just display the whole `check-info` stack.

The default value for #:mode is 'quiet.

2019-03-23 18:03 UTC, kazk commented
Looking good. But the `'quiet` mode is missing `expected`.

![image](https://user-images.githubusercontent.com/639336/54869799-f8ea2280-4d5a-11e9-8cdf-781f7adf8b89.png)

You can try this on Codewars if that helps. Just paste the contents of `codewars/rackunit.rkt` in Kumite and run some tests.

2019-03-23 18:06 UTC, kazk requested changes
I think everything else looks better. Thanks adding some comments too :)
Please fix the missing expected.

2019-03-24 14:24 UTC, yfzhe commented
@kazk I think this PR is ready.

2019-03-24 19:43 UTC, kazk commented
Is it possible to show `message` without the quotes?

For example,
```racket
(check-equal? (f "foo" "bar") "foobar" (format "(f ~s ~s)" "foo" "bar"))
```
will show
```
message:   "(f \"foo\" \"bar\")"
```
can this be
```
message:   (f "foo" "bar")
```
?

2019-03-25 08:06 UTC, yfzhe commented
Of course we can. However, it is how we show the `check-info`s that we get the value part of `check-info`, and transform them into strings in [`write`](https://docs.racket-lang.org/guide/read-write.html) mode, and then display them. (And rackunit does also behave like this.)

1. We can specially transform the 'message `check-info` in `display` mode. But inconsistent, isn't it?
2. Tell user to use [`string-info`](https://docs.racket-lang.org/rackunit/api.html?q=string-info#%28def._%28%28lib._rackunit%2Fmain..rkt%29._string-info%29%29) wrapper. It will make the 'message `check-info` works like how you want.
3. Just go back to how the `check-info` are shown. When a test failed, we display 
   ```
   Expected x, but instead got y.
   Message: blahblah
   ```

I prefer adding a new mode in `run-tests` for the third opinion.

2019-03-25 08:12 UTC, kazk approved these changes

2019-03-25 08:13 UTC, kazk commented
Hmm, then let's keep it as is for now and close #2. We can improve on this later in a separate PR if needed. Thanks again for your contribution.

2019-03-25 08:14 UTC, merged

2019-03-25 08:14 UTC, kazk commented
I'll let you know when I deploy this.